[server]
Address="0.0.0.0:40036"
LogLevel="Release"

[algo]
Address="http://0.0.0.0:5000"

[database]
uri = "mongodb://182.92.196.182:27017"
db = "kit"
connect = "replicaSet"
replica_set = ""
max_pool_size = 1024
min_pool_size = 8
max_idle_time = 5000
ssl = false
SQLAddress ="0.0.0.0:3306"
SQLName="root"
SQLPassword="Sense1236"
SQLDbName = "kit"
RedisAddress ="182.92.196.182:6379"